#!/usr/bin/env python3

import os
import sys
import helpers
import nltk

from analyzer import Analyzer
from termcolor import colored

def main():

    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets twitterhandle")

    tweets = (helpers.get_user_timeline(sys.argv[1][1:]))
    if tweets == None:
        sys.exit(1)

    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    analyzer = Analyzer(positives, negatives)
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(" {} {} {}", "green").format(score, tweet, sys.argv[1]))
        elif score < 0.0:
            print(colored("{} {} {}", "red").format(score, tweet, sys.argv[1]))
        else:
            print(colored(" {} {} {}", "yellow").format(score, tweet, sys.argv[1]))

if __name__ == "__main__":
    main()
